### ISSUE TITLE
[Feature request] make UUID bucket transformation optional as an UUID is often requested by cloud services

### ISSUE THREAD

**Issue by ealphonse** [NewMotion/akka-statsd#10]
Hello,

First of all, thank you for this StatsD driver.

By default, any UUID in the bucket path is substituted with token [id]. However, services like hostedgraphite requires to prefix the path with a valid client token, given as an UUID.

The driver cannot send data to these services as it obfuscates the identification token. It would be useful not to rely on any default, or to have a option to prevent this behavior from happening.

Best,

Erick

**Comment by kiequoo** [comment]
Addressed in https://github.com/NewMotion/akka-statsd/releases/tag/v3.0.7

**Comment by ealphonse** [comment]
@kiequoo thank you
