### ISSUE TITLE
Artifact has disappeared from Maven?

### ISSUE THREAD

**Issue by bhoggard** [NewMotion/akka-statsd#11]
```scala
libraryDependencies += "com.newmotion" %% "akka-statsd-core" % "2.0.0"
```
results in an error:

> com.newmotion#akka-statsd-http-server_2.11;2.0.0: not found

I don't see it at 

https://mvnrepository.com/artifact/com.newmotion

or

https://oss.sonatype.org

either.

**Comment by poohsen** [comment]
Are you sure you were using 2.0.0 with Scala 2.11 before? 

EDIT
nvm, I see a 2.11 build of 2.0.0 on our company nexus.

**Comment by fedragon** [comment]
Hi @bhoggard,
version `2.0.0` has just been published to https://oss.sonatype.org/

Thanks for reporting this!
