### ISSUE TITLE
Sonatype artifact empty

### ISSUE THREAD

**Issue by Horneth** [NewMotion/akka-statsd#13]
It seems that artifacts are not published properly to sonatype. The highest version I can find is 2.1.3 and the jar seems empty (only contains the MANIFEST).

**Comment by poohsen** [comment]
Hi @Horneth, we're currentling experiencing difficulties with publishing to Sonatype. There's not enough time to conduct the thorough investigation that this would need, though, so right now we cannot provide a recent release via Sonatype, I'm afraid
