### ISSUE TITLE
Support for Scala 2.11

### ISSUE THREAD

**Issue by lxlyif** [NewMotion/akka-statsd#23]
Hi there,

I'm currently trying to work with your project with 2.11, however as stated in issue #13 the 2.11 version jars only contain MANIFEST. Since your problems posting to Sonatype seem to be fixed with the release of 3.0.3 for 2.12, I was wondering if we could expect a 2.11 version of 3.0.3.

Thanks!

**Comment by farico** [comment]
I second this!

**Comment by kiequoo** [comment]
Hi, I just published 3.0.6 on Sonatype for both Scala 2.11 and Scala 2.12!
